// text show only 100 charecter and then ...
EX: since the 1500...

<small>REQUESTER’S COMMENTS</small>
<p>{{ docketHistory.requesterComments | limitTo: 100 }}{{docketHistory.requesterComments.length > 100 ? '...' : ''}}</p>
